###

GET http://localhost:3000/user/getAll

###

POST http://localhost:3000/user/create
Content-Type: application/json

{
    "name" : "Nagalekha Ramesh",
    "email" : "ramesh.na@northeastern.edu",
    "password": "QWERTYa@123"
}

###

PUT http://localhost:3000/user/edit?email=keshava.ke@northeastern.edu
Content-Type: application/json

{
    "name": "Ruchika Shashidhara",
    "email": "ramesh.na@north.edu"
}

###

DELETE http://localhost:3000/user/delete?email=ruchi@northeastern.edu

###

